server:
  port: 9000
spring:
  application:
    name: oauth2-server
  datasource:
    url: jdbc:mysql://139.155.68.87:3306/oauth2?useUnocode=true&characterset=utf8
    username: root
    password: 123456